# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Weighted least-squares cross-products for beta-binomial IRLS
#'
#' Computes the symmetric information matrix \eqn{X^\top W X} and score
#' target \eqn{X^\top W z} in compiled code. This is an internal kernel used
#' by `bbreg()`.
#'
#' @param x Numeric design matrix.
#' @param weight Positive working-weight vector.
#' @param response Numeric working-response vector.
#' @return A list with `information` and `score_target`.
#' @keywords internal
bb_wls_system_cpp <- function(x, weight, response) {
    .Call('_CB2_bb_wls_system_cpp', PACKAGE = 'CB2', x, weight, response)
}

#' Compiled weighted least-squares solve for beta-binomial IRLS
#'
#' Forms \eqn{X^\top W X} and \eqn{X^\top W z}, solves the symmetric system,
#' and optionally returns its inverse in one compiled call.
#'
#' @param x Numeric design matrix.
#' @param weight Positive working-weight vector.
#' @param response Numeric working-response vector.
#' @param covariance Whether to return the inverse information matrix.
#' @return A list with `coefficient` and, when requested, `covariance`.
#' @keywords internal
bb_wls_solve_cpp <- function(x, weight, response, covariance = FALSE) {
    .Call('_CB2_bb_wls_solve_cpp', PACKAGE = 'CB2', x, weight, response, covariance)
}

#' A C++ function to quantify sgRNA abundance from NGS samples.
#'
#' @param ref_path the path of the annotation file and it has to be a FASTA formatted file.
#' @param fastq_path a list of the FASTQ files.
#' @param verbose Display some logs during the quantification if it is set to `true`.
#'
#' @importFrom Rcpp evalCpp
#' @useDynLib CB2
#' @export
quant <- function(ref_path, fastq_path, verbose = FALSE) {
    .Call('_CB2_quant', PACKAGE = 'CB2', ref_path, fastq_path, verbose)
}

#' A C++ function to perform a parameter estimation for the sgRNA-level test. 
#' It will estimate two different parameters `phat` and `vhat,`
#' and we assume input count data follows the beta-binomial distribution.
#' Dr. Keith Baggerly initially implemented this code in Matlab,
#' and it has been rewritten it in C++ for the speed-up.
#' 
#' @param xvec a matrix contains sgRNA read counts.
#' @param nvec a vector contains the library size.
#' 
#' @importFrom Rcpp evalCpp
#' @useDynLib CB2
#' @export
fit_ab <- function(xvec, nvec) {
    .Call('_CB2_fit_ab', PACKAGE = 'CB2', xvec, nvec)
}

